USE_MBOOT = 0
USE_PYDFU = 0

MCU_SERIES = h7
CMSIS_MCU = STM32H743xx
MICROPY_FLOAT_IMPL = single
AF_FILE = boards/stm32h743_af.csv
LD_FILES = boards/MY_H743_BOARD/stm32h743.ld
TEXT0_ADDR = 0x08000000

# Disable mbedTLS/network
MICROPY_PY_SSL = 0
MICROPY_SSL_MBEDTLS = 0
MICROPY_PY_LWIP = 0
MICROPY_PY_BLUETOOTH = 0

MBEDTLS_CONFIG_FILE = '"$(BOARD_DIR)/mbedtls_config_board.h"'
FROZEN_MANIFEST = $(BOARD_DIR)/manifest.py
