#ifndef MICROPY_INCLUDED_STM32H7XX_HAL_CONF_H
#define MICROPY_INCLUDED_STM32H7XX_HAL_CONF_H

#define HSE_VALUE (12000000)
#define LSE_VALUE (32768)

#define DATA_CACHE_ENABLE 1
#define INSTRUCTION_CACHE_ENABLE 1
#define PREFETCH_ENABLE 1
#define USE_RTOS 0

#define HAL_RNG_MODULE_ENABLED
#define HAL_SDRAM_MODULE_ENABLED
#define HAL_SD_MODULE_ENABLED
#define HAL_DCMI_MODULE_ENABLED
#define HAL_DAC_MODULE_ENABLED
#define HAL_ADC_MODULE_ENABLED

#include "boards/stm32h7xx_hal_conf_base.h"

#endif
